apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop-sre
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-redis.yaml
  - microservices.yaml
  - gateway-frontend.yaml
  - hpa.yaml
  - monitoring.yaml
