apiVersion: v1
kind: Secret
metadata:
  name: shop-secrets
  namespace: shop-sre
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
  POSTGRES_DB: shop
  ORDER_DB_USER: app
  ORDER_DB_PASSWORD: app
