[shop_nodes]
shop-vm ansible_host=127.0.0.1 ansible_user=ubuntu ansible_connection=local

[shop_nodes:vars]
project_dir=/opt/shop-sre
compose_file=docker-compose.yml
health_check_url=http://127.0.0.1:8088/
